### ISSUE TITLE
getting error during mvn install

### ISSUE THREAD

**Issue by omis76** [RusticiSoftware/TinCanJava#58]

**Comment by omis76** [comment]
sorry error is below-
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.                                                                                                                13:test (default-test) on project tincan: There are test failures.
[ERROR]

**Comment by omis76** [comment]
com.rusticisoftware.tincan.RemoteLRSTest  Time elapsed: 0.031 sec  <<< ERROR!
java.lang.NullPointerException: null
        at java.util.Properties$LineReader.readLine(Properties.java:434)
        at java.util.Properties.load0(Properties.java:353)
        at java.util.Properties.load(Properties.java:341)
        at com.rusticisoftware.tincan.RemoteLRSTest.Init(RemoteLRSTest.java:68)
